name: Build and Deploy React App

on:
  push:
    branches:
      - frontend-production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: CI=false npm run build

      - name: Deploy to Build Branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # ایجاد شاخه جدید به نام client-build
          git checkout --orphan client-build
          
          # حذف همه فایل‌ها از پوشه پروژه (برای پاک کردن فضای کاری)
          git rm -rf .
          
          # انتقال محتوای پوشه build به شاخه client-build
          mv build/* ./  # این دستور تمام فایل‌های داخل build را به ریشه پروژه منتقل می‌کند
          
          # اضافه کردن تغییرات به مخزن گیت
          git add -A
          
          # انجام commit و ارسال تغییرات
          git commit -m "Deploy build folder"
          
          # ارسال تغییرات به شاخه client-build
          git push --set-upstream origin client-build --force
