name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debugging SSH Setup
        run: |
           echo "${{ secrets.SSH_PRIVATE_KEY }}" || echo "SSH_PRIVATE_KEY is missing!"
