name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check if SSH key exists
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" || echo "SSH_PRIVATE_KEY is missing!"

