name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # گام 1: کلون کردن کد مخزن
    - name: Checkout code
      uses: actions/checkout@v3

    # گام 2: ایجاد پوشه SSH و تنظیم کلید خصوصی
    - name: Setup SSH
      run: |
           echo "${{ secrets.SSH_PRIVATE_KEY }}" || echo "SSH_PRIVATE_KEY is missing!"
