name: Test SSH Connection

on: 
  push:
    branches:
      - main  # یا هر شاخه‌ای که می‌خواهید

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh  # ایجاد پوشه .ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa  # نوشتن کلید SSH در id_rsa
          chmod 600 ~/.ssh/id_rsa  # تنظیم مجوزهای فایل
          ssh-keyscan your-server-ip >> ~/.ssh/known_hosts  # اضافه کردن سرور به known_hosts

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -T user@your-server-ip "echo 'SSH connection successful!'"
