name: Test SSH Connection

on: 
  push:
    branches:
      - main  # یا هر شاخه‌ای که می‌خواهید

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          # ایجاد پوشه .ssh
          mkdir -p ~/.ssh
          # نمایش محتوای کلید برای عیب‌یابی (فقط برای تست)
          echo "${{ secrets.SSH_PRIVATE_KEY }}"
          # ذخیره کلید SSH در id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # تنظیم مجوزهای فایل
          # اضافه کردن سرور به known_hosts
          ssh-keyscan 87.248.150.99 >> ~/.ssh/known_hosts
          # بررسی صحت فایل id_rsa و دسترسی‌ها
          ls -l ~/.ssh
          cat ~/.ssh/id_rsa

      - name: Test SSH connection
        run: |
          # تست اتصال SSH
          ssh -o StrictHostKeyChecking=no -T user@87.248.150.99 "echo 'SSH connection successful!'"
