name: Deploy React App

on:
  push:
    branches:
      - frontend-production # برنچ مربوطه برای دیپلوی

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. چک کردن کدهای مخزن
    - name: Checkout Code
      uses: actions/checkout@v3
      
    # 3. تأیید نسخه‌های نصب شده
    - name: Verify Node.js and npm versions
      run: |
        node -v
        npm -v
