name: Advanced Deploy Workflow

on:
  push:
    branches:
      - frontend-production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Setup SSH
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 9011 -H 87.248.150.99 >> ~/.ssh/known_hosts

    # 3. Check and Install Node.js and npm
    - name: Verify and Install Node.js and npm
      run: |
        ssh -p 9011 -o StrictHostKeyChecking=no app@87.248.150.99 << 'EOF'
        # Check for Node.js
        NODE_VERSION=$(node -v 2>/dev/null || echo "none")
        if [[ "$NODE_VERSION" != "v20.11.1" ]]; then
          echo "Node.js not found or version incorrect. Installing Node.js 20.11.1..."
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
        else
          echo "Node.js version $NODE_VERSION is already installed."
        fi

        # Check for npm
        NPM_VERSION=$(npm -v 2>/dev/null || echo "none")
        if [[ "$NPM_VERSION" != "10.2.4" ]]; then
          echo "npm not found or version incorrect. Installing npm 10.2.4..."
          sudo npm install -g npm@10.2.4
        else
          echo "npm version $NPM_VERSION is already installed."
        fi
        EOF
