name: Full Deployment Workflow

on:
  push:
    branches:
      - frontend-production # Branch for production deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Match Node.js version with your local machine

      # 3. Install Dependencies
      - name: Install Dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --legacy-peer-deps
          fi

      # 4. Add Missing Babel Dependency (Optional, if needed)
      - name: Add Missing Dependencies
        run: npm install @babel/plugin-proposal-private-property-in-object --save-dev

      # 5. Build the React App
      - name: Build React App
        run: |
          NODE_OPTIONS="--max_old_space_size=4096" npm run build

      # 6. Upload the Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build

      # 7. Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 9011 -H 87.248.150.99 >> ~/.ssh/known_hosts

      # 8. Deploy Build to Server
      - name: Deploy Build to Server
        run: |
          ssh -p 9011 -o StrictHostKeyChecking=no app@87.248.150.99 "
          mkdir -p /home/app/delta &&
          rm -rf /home/app/delta/build &&
          mkdir -p /home/app/delta/build
          "
          scp -P 9011 -r ./build/* app@87.248.150.99:/home/app/delta/build/

      # 9. Serve Application with pm2
      - name: Serve Application with pm2
        run: |
          ssh -p 9011 -o StrictHostKeyChecking=no app@87.248.150.99 "
          export NVM_DIR=\"\$HOME/.nvm\" &&
          [ -s \"\$NVM_DIR/nvm.sh\" ] && \. \"\$NVM_DIR/nvm.sh\" &&
          npm install -g pm2 serve &&
          pm2 delete delta-app || true &&
          pm2 start serve --name delta-app -- -s /home/app/delta/build -l 3000
          "
