name: Deploy React App

on:
  push:
    branches:
      - frontend-production # برنچ مربوطه برای دیپلوی

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Check Repository
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 9011 -H 87.248.150.99 >> ~/.ssh/known_hosts

    # 2. تأیید نسخه‌های نصب شده
    - name: Verify Node.js and npm versions
      run: |
        node -v
        npm -v
        

