name: Full Deployment Workflow

on:
  push:
    branches:
      - frontend-production # برنچ مخصوص دیپلوی

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 9011 -H 87.248.150.99 >> ~/.ssh/known_hosts

      # 3. Install Node.js using nvm
      - name: Install Node.js with nvm
        run: |
          ssh -p 9011 -o StrictHostKeyChecking=no app@87.248.150.99 "
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash &&
          export NVM_DIR=\"\$HOME/.nvm\" &&
          [ -s \"\$NVM_DIR/nvm.sh\" ] && \. \"\$NVM_DIR/nvm.sh\" &&
          nvm install 20.11.1 &&
          nvm use 20.11.1 &&
          nvm alias default 20.11.1
          "

      # 4. Build the React App
      - name: Build React App
        run: |
          ssh -p 9011 -o StrictHostKeyChecking=no app@87.248.150.99 "
          export NVM_DIR=\"\$HOME/.nvm\" &&
          [ -s \"\$NVM_DIR/nvm.sh\" ] && \. \"\$NVM_DIR/nvm.sh\" &&
          cd /home/app &&
          rm -rf project &&
          git clone https://github.com/your-org/your-repo.git project &&
          cd project &&
          npm install &&
          npm run build
          "

      # 5. Copy Build to Delta Directory
      - name: Deploy Build
        run: |
          ssh -p 9011 -o StrictHostKeyChecking=no app@87.248.150.99 "
          mkdir -p /home/app/delta &&
          cp -r /home/app/project/build/* /home/app/delta
          "

      # 6. Install pm2 Globally and Serve the Application
      - name: Serve Application with pm2
        run: |
          ssh -p 9011 -o StrictHostKeyChecking=no app@87.248.150.99 "
          export NVM_DIR=\"\$HOME/.nvm\" &&
          [ -s \"\$NVM_DIR/nvm.sh\" ] && \. \"\$NVM_DIR/nvm.sh\" &&
          npm install -g pm2 serve &&
          pm2 delete react-app || true &&
          pm2 start serve --name react-app -- -s /home/app/delta -l 3000
          "
